In [2]:
import numpy as np
import pandas as pd
import sklearn

In [5]:
data = pd.read_csv("data.csv")

In [20]:
test_data = pd.DataFrame()

In [9]:
data.is_goal.describe()

count    24429.000000
mean         0.445331
std          0.497013
min          0.000000
25%          0.000000
50%          0.000000
75%          1.000000
max          1.000000
Name: is_goal, dtype: float64

In [17]:
data.count

<bound method DataFrame.count of        Unnamed: 0  match_event_id  location_x  location_y  remaining_min  \
0               0            10.0       167.0        72.0           10.0
1               1            12.0      -157.0         0.0           10.0
2               2            35.0      -101.0       135.0            7.0
3               3            43.0       138.0       175.0            6.0
4               4           155.0         0.0         0.0            NaN
5               5           244.0      -145.0       -11.0            9.0
6               6           251.0         0.0         0.0            8.0
7               7           254.0         1.0        28.0            8.0
8               8           265.0       -65.0         NaN            6.0
9               9           294.0       -33.0         NaN            3.0
10             10           309.0       -94.0       238.0            1.0
11             11             4.0       121.0       127.0           11.0
12             12            27.0       -67.0         NaN            7.0
13             13            66.0       -94.0         4.0            NaN
14             14            80.0       -23.0        47.0            1.0
15             15            86.0         NaN       192.0            0.0
16             16           100.0         0.0         0.0            0.0
17             17           138.0      -117.0       226.0            8.0
18             18           244.0         NaN        97.0           11.0
19             19           249.0         0.0         0.0           10.0
20             20           255.0         3.0       144.0           10.0
21             21           265.0       134.0       127.0            9.0
22             22           274.0       -16.0       110.0            7.0
23             23           299.0      -109.0       150.0            5.0
24             24           307.0       -46.0        63.0            5.0
25             25           332.0         0.0         0.0            2.0
26             26           345.0         NaN       196.0            2.0
27             27           369.0      -183.0       186.0            0.0
28             28           400.0        85.0       173.0            8.0
29             29           429.0         3.0        87.0            6.0
...           ...             ...         ...         ...            ...
30667       30667           368.0        40.0       250.0            9.0
30668       30668           386.0       -23.0       222.0            7.0
30669       30669           425.0       171.0        53.0            3.0
30670       30670             NaN       -74.0        16.0            9.0
30671       30671            25.0         0.0         0.0            8.0
30672       30672            29.0        89.0        55.0            8.0
30673       30673             NaN       117.0         0.0            NaN
30674       30674            81.0       117.0       216.0            2.0
30675       30675            84.0      -134.0         NaN            2.0
30676       30676            98.0      -141.0         0.0            0.0
30677       30677           101.0         NaN       143.0            0.0
30678       30678           181.0        14.0        16.0            3.0
30679       30679           212.0         0.0         0.0            0.0
30680       30680           213.0         0.0         0.0            0.0
30681       30681           218.0       -18.0       261.0            0.0
30682       30682           226.0         NaN        48.0           11.0
30683       30683           228.0         1.0       216.0           10.0
30684       30684           231.0       -96.0        89.0           10.0
30685       30685           249.0        81.0       250.0            7.0
30686       30686           268.0        16.0        93.0            5.0
30687       30687           284.0        40.0       100.0            3.0
30688       30688           308.0      -126.0        61.0            1.0
30689       30689           326.0       -12.0       679.0            0.0
30690       30690           331.0      -113.0       100.0           11.0
30691       30691           382.0         0.0         0.0            NaN
30692       30692           397.0         1.0        48.0            6.0
30693       30693           398.0         0.0         0.0            6.0
30694       30694           426.0      -134.0       166.0            3.0
30695       30695           448.0        31.0       267.0            2.0
30696       30696           471.0         1.0         NaN            0.0

       power_of_shot  knockout_match game_season  remaining_sec  \
0                1.0             0.0     2000-01           27.0
1                1.0             0.0     2000-01           22.0
2                1.0             0.0     2000-01           45.0
3                1.0             0.0     2000-01           52.0
4                2.0             0.0     2000-01           19.0
5                3.0             0.0         NaN           32.0
6                NaN             0.0     2000-01           52.0
7                3.0             0.0     2000-01            5.0
8                3.0             0.0     2000-01           12.0
9                3.0             0.0     2000-01           36.0
10               3.0             0.0     2000-01           56.0
11               1.0             0.0     2000-01            0.0
12               1.0             0.0         NaN            NaN
13               1.0             0.0     2000-01           44.0
14               1.0             0.0     2000-01           16.0
15               1.0             0.0     2000-01            NaN
16               1.0             0.0     2000-01            1.0
17               2.0             0.0     2000-01           50.0
18               3.0             0.0     2000-01           29.0
19               3.0             0.0         NaN           46.0
20               3.0             0.0     2000-01            8.0
21               3.0             0.0         NaN            4.0
22               3.0             0.0     2000-01           57.0
23               3.0             0.0         NaN           47.0
24               3.0             0.0     2000-01           11.0
25               3.0             0.0     2000-01           36.0
26               3.0             0.0     2000-01            4.0
27               3.0             0.0     2000-01           30.0
28               4.0             0.0     2000-01            NaN
29               4.0             0.0     2000-01           22.0
...              ...             ...         ...            ...
30667            4.0             1.0     1999-00           33.0
30668            4.0             1.0     1999-00           27.0
30669            4.0             1.0         NaN           48.0
30670            1.0             1.0     1999-00           34.0
30671            1.0             1.0     1999-00           51.0
30672            1.0             1.0     1999-00            9.0
30673            1.0             1.0         NaN           14.0
30674            1.0             1.0     1999-00           34.0
30675            1.0             1.0         NaN            0.0
30676            1.0             1.0     1999-00            NaN
30677            1.0             1.0     1999-00            1.0
30678            2.0             NaN     1999-00           34.0
30679            2.0             1.0     1999-00           41.0
30680            2.0             1.0         NaN           40.0
30681            2.0             1.0     1999-00            2.0
30682            3.0             1.0     1999-00           30.0
30683            NaN             1.0     1999-00           51.0
30684            3.0             1.0         NaN           16.0
30685            3.0             NaN     1999-00           31.0
30686            3.0             1.0         NaN           37.0
30687            3.0             1.0     1999-00           18.0
30688            3.0             1.0     1999-00            7.0
30689            3.0             1.0     1999-00            0.0
30690            4.0             1.0     1999-00           37.0
30691            4.0             1.0     1999-00            4.0
30692            4.0             1.0     1999-00            5.0
30693            4.0             1.0     1999-00            5.0
30694            4.0             1.0     1999-00           28.0
30695            4.0             1.0     1999-00           10.0
30696            4.0             1.0     1999-00           39.0

       distance_of_shot        ...                         lat/lng  \
0                  38.0        ...          45.539131, -122.651648
1                  35.0        ...          45.539131, -122.651648
2                  36.0        ...          45.539131, -122.651648
3                  42.0        ...          45.539131, -122.651648
4                  20.0        ...          45.539131, -122.651648
5                  34.0        ...          45.539131, -122.651648
6                  20.0        ...          45.539131, -122.651648
7                  22.0        ...          45.539131, -122.651648
8                  32.0        ...          45.539131, -122.651648
9                  32.0        ...          45.539131, -122.651648
10                 45.0        ...          45.539131, -122.651648
11                 37.0        ...           42.982923, -71.446094
12                  NaN        ...           42.982923, -71.446094
13                 29.0        ...           42.982923, -71.446094
14                 25.0        ...           42.982923, -71.446094
15                 40.0        ...           42.982923, -71.446094
16                 20.0        ...           42.982923, -71.446094
17                 45.0        ...           42.982923, -71.446094
18                 36.0        ...           42.982923, -71.446094
19                 20.0        ...           42.982923, -71.446094
20                 34.0        ...           42.982923, -71.446094
21                 38.0        ...           42.982923, -71.446094
22                 31.0        ...           42.982923, -71.446094
23                 38.0        ...           42.982923, -71.446094
24                 27.0        ...           42.982923, -71.446094
25                 20.0        ...           42.982923, -71.446094
26                 40.0        ...           42.982923, -71.446094
27                 46.0        ...           42.982923, -71.446094
28                 39.0        ...           42.982923, -71.446094
29                 28.0        ...           42.982923, -71.446094
...                 ...        ...                             ...
30667              45.0        ...           40.361408, -86.186052
30668              42.0        ...                             NaN
30669              37.0        ...           40.361408, -86.186052
30670              27.0        ...           42.982923, -71.446094
30671              20.0        ...           42.982923, -71.446094
30672              30.0        ...           42.982923, -71.446094
30673              31.0        ...           42.982923, -71.446094
30674              44.0        ...           42.982923, -71.446094
30675              45.0        ...           42.982923, -71.446094
30676              34.0        ...           42.982923, -71.446094
30677              38.0        ...           42.982923, -71.446094
30678               NaN        ...           42.982923, -71.446094
30679              20.0        ...           42.982923, -71.446094
30680              20.0        ...           42.982923, -71.446094
30681              46.0        ...           42.982923, -71.446094
30682              28.0        ...           42.982923, -71.446094
30683              41.0        ...           42.982923, -71.446094
30684              33.0        ...           42.982923, -71.446094
30685              46.0        ...           42.982923, -71.446094
30686              29.0        ...           42.982923, -71.446094
30687              30.0        ...           42.982923, -71.446094
30688              33.0        ...           42.982923, -71.446094
30689              87.0        ...           42.982923, -71.446094
30690              35.0        ...           42.982923, -71.446094
30691              20.0        ...           42.982923, -71.446094
30692              24.0        ...           42.982923, -71.446094
30693              20.0        ...           42.982923, -71.446094
30694              41.0        ...                             NaN
30695              46.0        ...           42.982923, -71.446094
30696              27.0        ...           42.982923, -71.446094

      type_of_shot type_of_combined_shot  match_id     team_id  \
0        shot - 30                   NaN  20000012  1610612747
1        shot - 45                   NaN  20000012  1610612747
2        shot - 25                   NaN  20000012  1610612747
3              NaN              shot - 3  20000012  1610612747
4              NaN              shot - 1  20000012  1610612747
5        shot - 17                   NaN  20000012  1610612747
6              NaN              shot - 4  20000012  1610612747
7              NaN              shot - 3  20000012  1610612747
8        shot - 36                   NaN  20000012  1610612747
9        shot - 44                   NaN  20000012  1610612747
10        shot - 7                   NaN  20000012  1610612747
11             NaN              shot - 3  20000019  1610612747
12       shot - 44                   NaN  20000019  1610612747
13             NaN              shot - 3  20000019  1610612747
14       shot - 12                   NaN  20000019  1610612747
15             NaN              shot - 3  20000019  1610612747
16             NaN              shot - 4  20000019  1610612747
17        shot - 6                   NaN  20000019  1610612747
18             NaN              shot - 3  20000019  1610612747
19        shot - 4                   NaN  20000019  1610612747
20       shot - 20                   NaN  20000019  1610612747
21       shot - 24                   NaN  20000019  1610612747
22       shot - 44                   NaN  20000019  1610612747
23             NaN              shot - 3  20000019  1610612747
24             NaN              shot - 3  20000019  1610612747
25             NaN              shot - 4  20000019  1610612747
26       shot - 30                   NaN  20000019  1610612747
27       shot - 54                   NaN  20000019  1610612747
28             NaN              shot - 3  20000019  1610612747
29       shot - 42                   NaN  20000019  1610612747
...            ...                   ...       ...         ...
30667          NaN              shot - 3  49900087  1610612747
30668          NaN              shot - 3  49900087  1610612747
30669          NaN              shot - 3  49900087  1610612747
30670          NaN              shot - 3  49900088  1610612747
30671          NaN              shot - 4  49900088  1610612747
30672    shot - 33                   NaN  49900088  1610612747
30673          NaN              shot - 3  49900088  1610612747
30674          NaN              shot - 3  49900088  1610612747
30675          NaN              shot - 3  49900088  1610612747
30676    shot - 44                   NaN  49900088  1610612747
30677          NaN              shot - 3  49900088  1610612747
30678          NaN              shot - 4  49900088  1610612747
30679    shot - 39                   NaN  49900088  1610612747
30680    shot - 49                   NaN  49900088  1610612747
30681    shot - 17                   NaN  49900088  1610612747
30682    shot - 44                   NaN  49900088  1610612747
30683    shot - 38                   NaN  49900088  1610612747
30684    shot - 37                   NaN  49900088  1610612747
30685          NaN              shot - 3  49900088  1610612747
30686    shot - 44                   NaN  49900088  1610612747
30687    shot - 54                   NaN  49900088  1610612747
30688          NaN              shot - 3  49900088  1610612747
30689          NaN              shot - 3  49900088  1610612747
30690          NaN              shot - 3  49900088  1610612747
30691     shot - 4                   NaN  49900088  1610612747
30692     shot - 1                   NaN  49900088  1610612747
30693    shot - 49                   NaN  49900088  1610612747
30694          NaN              shot - 3  49900088  1610612747
30695    shot - 26                   NaN  49900088  1610612747
30696    shot - 45                   NaN  49900088  1610612747

      remaining_min.1 power_of_shot.1  knockout_match.1 remaining_sec.1  \
0               10.00            1.00            50.608         54.2000
1               10.00            1.00            28.800         22.0000
2               92.64            1.00             0.000         63.7216
3                 NaN            1.00           122.608         52.0000
4               42.64            2.00             0.000         19.0000
5                9.00            3.00             0.000             NaN
6                8.00            3.00             0.000        112.2000
7               68.64            3.00             0.000          5.0000
8                6.00            3.00             0.000         12.0000
9                3.00            3.00             0.000         52.2000
10                NaN            3.00            80.928         56.0000
11              11.00            1.00           106.608         64.7856
12               7.00           77.36             0.000          9.0000
13               2.00           68.36             0.000         44.0000
14               1.00            1.00             0.000         16.0000
15              94.64           70.36             0.000         70.7856
16               0.00            1.00             0.000          1.0000
17              38.64            2.00             0.000         50.0000
18              11.00            3.00             0.000         29.0000
19              10.00           70.36             0.000         46.0000
20              10.00            3.00             0.000          8.0000
21               9.00           43.36             0.000          4.0000
22               7.00            3.00             0.000         57.0000
23               5.00            3.00             0.000         47.0000
24               5.00            3.00             0.000         25.2000
25              93.64            3.00             0.000         36.0000
26               2.00           83.36             0.000         63.7856
27               0.00            3.00             0.000         30.0000
28               8.00            4.00            61.928         19.0000
29              73.64            4.00             0.000         22.0000
...               ...             ...               ...             ...
30667            9.00            4.00             1.000         33.0000
30668            7.00           68.36            54.608         27.0000
30669            3.00            4.00             1.000        112.7856
30670           38.64            1.00             1.000         34.0000
30671            8.00          102.36             1.000         51.0000
30672          109.64           29.36             1.000          9.0000
30673            7.00           63.36             1.000         14.0000
30674            2.00            1.00             1.000         34.0000
30675            2.00            1.00            34.928          0.0000
30676            0.00            1.00             1.000         37.0000
30677            0.00            1.00             1.000          1.0000
30678            3.00           29.36             1.000         34.0000
30679           71.64            2.00             1.000         41.0000
30680            0.00            2.00           121.928         40.0000
30681           68.64            2.00             1.000          2.0000

In [28]:
if data.is_goal.isnull() == False

0         True
1        False
2        False
3        False
4        False
5        False
6        False
7         True
8        False
9        False
10       False
11       False
12       False
13       False
14       False
15       False
16        True
17       False
18       False
19        True
20       False
21        True
22       False
23       False
24       False
25       False
26       False
27       False
28       False
29       False
         ...
30667    False
30668     True
30669    False
30670    False
30671    False
30672    False
30673    False
30674    False
30675    False
30676    False
30677    False
30678    False
30679     True
30680     True
30681     True
30682     True
30683    False
30684    False
30685    False
30686     True
30687     True
30688    False
30689    False
30690    False
30691    False
30692    False
30693     True
30694    False
30695    False
30696    False
Name: is_goal, Length: 30697, dtype: bool

In [43]:
test_data = data.loc[data.is_goal.isnull()]

In [44]:
test_data.shape

(6268, 28)

In [45]:
test_data.head(10)
# will need reindexing

,Unnamed: 0,match_event_id,location_x,location_y,remaining_min,power_of_shot,knockout_match,game_season,remaining_sec,distance_of_shot,...,lat/lng,type_of_shot,type_of_combined_shot,match_id,team_id,remaining_min.1,power_of_shot.1,knockout_match.1,remaining_sec.1,distance_of_shot.1
0,0,10.0,167.0,72.0,10.0,1.0,0.0,2000-01,27.0,38.0,...,"45.539131, -122.651648",shot - 30,NaN,20000012,1610612747,10.00,1.00,50.608,54.2,38.0
7,7,254.0,1.0,28.0,8.0,3.0,0.0,2000-01,5.0,22.0,...,"45.539131, -122.651648",NaN,shot - 3,20000012,1610612747,68.64,3.00,0.000,5.0,22.0
16,16,100.0,0.0,0.0,0.0,1.0,0.0,2000-01,1.0,20.0,...,"42.982923, -71.446094",NaN,shot - 4,20000019,1610612747,0.00,1.00,0.000,1.0,20.0
19,19,249.0,0.0,0.0,10.0,3.0,0.0,NaN,46.0,20.0,...,"42.982923, -71.446094",shot - 4,NaN,20000019,1610612747,10.00,70.36,0.000,46.0,20.0
21,21,265.0,134.0,127.0,9.0,3.0,0.0,NaN,4.0,38.0,...,"42.982923, -71.446094",shot - 24,NaN,20000019,1610612747,9.00,43.36,0.000,4.0,38.0
32,32,4.0,163.0,76.0,11.0,1.0,0.0,2000-01,26.0,37.0,...,"49.250068, -123.114646",shot - 34,NaN,20000047,1610612747,11.00,1.00,0.000,26.0,37.0
33,33,8.0,70.0,194.0,10.0,1.0,0.0,2000-01,58.0,40.0,...,"49.250068, -123.114646",NaN,shot - 3,20000047,1610612747,10.00,1.00,121.608,58.0,40.0
34,34,26.0,1.0,19.0,7.0,1.0,0.0,2000-01,33.0,21.0,...,"49.250068, -123.114646",shot - 39,NaN,20000047,1610612747,NaN,1.00,0.000,33.0,21.0
35,35,37.0,-12.0,NaN,5.0,1.0,0.0,2000-01,58.0,21.0,...,"49.250068, -123.114646",shot - 39,NaN,20000047,1610612747,5.00,104.36,102.608,58.0,84.4
36,36,53.0,1.0,4.0,4.0,1.0,0.0,2000-01,9.0,20.0,...,"49.250068, -123.114646",NaN,shot - 4,20000047,1610612747,108.64,1.00,0.000,9.0,59.4